In [1]:
import torch
from torch import nn # nn contains all of PyTorch's building blocks for neural networks
import matplotlib.pyplot as plt

In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
#  Get the  python number within a tensor (only works with one-element tensors)
scalar.item()

7

In [4]:
scalar.ndim

0

In [5]:
import numpy as np

In [6]:
one = np.array(1)
print(one.shape)

()


In [7]:
print(one.ndim)


0


In [8]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [9]:
# check the number of dimensions of vectors
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
# Check number of dimension
MATRIX.ndim

2

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR.ndim

3

In [17]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3,5)
random_tensor

tensor([[0.6723, 0.1607, 0.8867, 0.4128, 0.0408],
        [0.8471, 0.6344, 0.4770, 0.0705, 0.0725],
        [0.0860, 0.8167, 0.2992, 0.5311, 0.7485]])

In [18]:
random_tensor.dtype

torch.float32

In [19]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([224, 224, 3]), 3)

In [20]:
# use torch.arrange(), torch.range() is deprecated
zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future

C:\Users\user322\AppData\Local\Temp\ipykernel_9560\261240356.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future


In [21]:
# Zeros and Ones
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [22]:
# create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

# Creating a range and tensors like

In [23]:
# Sometimes you want a range of numbers such as 1 to 10 or 0 to 100
# you can (start, end , step) 

# Use torch.arange(), torch.range() is deprecated
zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future

# Create  a range of values 0 to 10
zeros_to_ten = torch.arange(start=0, end=10, step=1)
zeros_to_ten

C:\Users\user322\AppData\Local\Temp\ipykernel_9560\3847230605.py:5: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
# sometimes you might want one tensor of certain type with the same shape as another tensor

# can also create a tensor of zeroes similar to another tensor
ten_zeros = torch.zeros_like(input=zeros_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor datatypes

In [25]:
# Default datatypes for tensors is float32
float_32_tensor = torch.tensor([9.0, 9.0, 9.0],
                               dtype=None, 
                               device=None,
                               requires_grad=False)  
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [26]:

float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float32) # torch.half would also work
float_16_tensor.dtype

torch.float32

# Getting information from tensors

In [27]:
# Create a tensor 
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"The datatype: {some_tensor.dtype}")
print(f"The devices: {some_tensor.device}")
print(f"The shape: {some_tensor.shape}")

tensor([[0.9504, 0.8617, 0.5373, 0.4816],
        [0.2844, 0.6280, 0.3376, 0.8713],
        [0.4378, 0.1027, 0.3341, 0.1172]])
The datatype: torch.float32
The devices: cpu
The shape: torch.Size([3, 4])


# Manipulating tensors (tensor operations)

In [28]:
# Basic operations
# Create a tensor of values and add a number to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [29]:
# Multiply it by 10
tensor * 10


tensor([10, 20, 30])

In [30]:
# Tensors don't change unless reassigned
tensor

tensor([1, 2, 3])

In [31]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [32]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [33]:
# Can also use torch functions
torch.multiply(tensor, 10)


tensor([10, 20, 30])

In [34]:
# Original tensor is still unchanged
tensor

tensor([1, 2, 3])

In [35]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1 ->1, 2 ->2)
print(tensor, "*", tensor)
print("Equals:",  tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


# Matrix multiplication (is all you need)

In [36]:
import torch
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

In [37]:
# Element-wise matrix multiplication
tensor * tensor

tensor([1, 4, 9])

In [38]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [39]:
# Can also use the "@" symbol for matrix multiplication, though not recommended
tensor @ tensor

tensor(14)

In [40]:
%%time
# Matrix multiplication by hand
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: total: 0 ns
Wall time: 106 ms


tensor(14)

In [41]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 197 μs


tensor(14)

# One of the most common errors in deep learning (shape errors)

In [42]:
# Shape need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)
                         
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)
torch.matmul(tensor_A, tensor_B) # (this will error)                         

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [43]:
# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [44]:
# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)


tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [45]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A}, (same as above), tensor_B.T = {tensor_B.shape}\n")
print(f"Multiplying: {tensor_A} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output: \n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")


Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = tensor([[1., 2.],
        [3., 4.],
        [5., 6.]]), (same as above), tensor_B.T = torch.Size([3, 2])

Multiplying: tensor([[1., 2.],
        [3., 4.],
        [5., 6.]]) * torch.Size([2, 3]) <- inner dimensions match

Output: 

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [46]:
# torch.mm is a shortcut for matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [47]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2,   # in_features = matches inner dimension of input
                         out_features=6) # out_features = describes outer value
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"output:\n{output}\n\noutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

output shape: torch.Size([3, 6])


# Finding the min , max, mean, sum, etc (aggregation)

In [48]:
# create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [49]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}) # this will bring error
print(f"Mean: {x.type(torch.float32).mean()}") # won't  work without float datatype
print(f"sum: {x.sum()}")


Minimum: 0
Maximum: 90
Mean: 45.0
sum: 450


In [50]:
x.min()

tensor(0)

In [51]:
torch.max(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(45.), tensor(450))

# Positional min/max

In [52]:
# create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


# Change tensor datatype

In [53]:
# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [54]:
# create a float16 tensor
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [55]:
# Create an int8 tensor
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

In [57]:
# create a tensor
import torch
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [58]:
# Add an extra dimension
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [61]:
# Change view (keeps same data as original but changes view)
# see more: htt://stackoverflow.com/a/54507446/7900723
z = x.view(1, 7)
z
# z, z.shape

tensor([[1., 2., 3., 4., 5., 6., 7.]])

In [62]:
# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [63]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)  # try changing dim to dim=1 and see what happens
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [66]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")
# Remove extra dimension from x_reshape
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [67]:
# create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2 , 2 ->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


# Indexing (Selecting data from tensors)

In [68]:
# create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [69]:
# Let's index bracket by bracket 
print(f"First square bracket: \n{x[0]}")
print(f"Second square bracket: {x[0][0]}")
print(f"Third square brackets: {x[0][0][0]}")

First square bracket: 
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square brackets: 1
