In [1]:
import torch
from torch import nn # nn contains all of PyTorch's building blocks for neural networks
import matplotlib.pyplot as plt

In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
#  Get the  python number within a tensor (only works with one-element tensors)
scalar.item()

7

In [4]:
scalar.ndim

0

In [5]:
import numpy as np

In [6]:
one = np.array(1)
print(one.shape)

()


In [7]:
print(one.ndim)


0


In [8]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [9]:
# check the number of dimensions of vectors
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
# Check number of dimension
MATRIX.ndim

2

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR.ndim

3

In [17]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3,5)
random_tensor

tensor([[0.4865, 0.8478, 0.8498, 0.4954, 0.9612],
        [0.4178, 0.8777, 0.6854, 0.6106, 0.8586],
        [0.4372, 0.3225, 0.1805, 0.9737, 0.1348]])

In [18]:
random_tensor.dtype

torch.float32

In [19]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([224, 224, 3]), 3)

In [20]:
# use torch.arrange(), torch.range() is deprecated
zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future

C:\Users\user322\AppData\Local\Temp\ipykernel_3344\261240356.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future


In [21]:
# Zeros and Ones
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [22]:
# create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

# Creating a range and tensors like

In [24]:
# Sometimes you want a range of numbers such as 1 to 10 or 0 to 100
# you can (start, end , step) 

# Use torch.arange(), torch.range() is deprecated
zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future

# Create  a range of values 0 to 10
zeros_to_ten = torch.arange(start=0, end=10, step=1)
zeros_to_ten

C:\Users\user322\AppData\Local\Temp\ipykernel_3344\3847230605.py:5: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# sometimes you might want one tensor of certain type with the same shape as another tensor

# can also create a tensor of zeroes similar to another tensor
ten_zeros = torch.zeros_like(input=zeros_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor datatypes

In [27]:
# Default datatypes for tensors is float32
float_32_tensor = torch.tensor([9.0, 9.0, 9.0],
                               dtype=None, 
                               device=None,
                               requires_grad=False)  
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [32]:

float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float32) # torch.half would also work
float_16_tensor.dtype

torch.float32

# Getting information from tensors

In [33]:
# Create a tensor 
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"The datatype: {some_tensor.dtype}")
print(f"The devices: {some_tensor.device}")
print(f"The shape: {some_tensor.shape}")

tensor([[0.9850, 0.0646, 0.5253, 0.9271],
        [0.0333, 0.6694, 0.1541, 0.5057],
        [0.7883, 0.4981, 0.1978, 0.3608]])
The datatype: torch.float32
The devices: cpu
The shape: torch.Size([3, 4])


# Manipulating tensors (tensor operations)

In [34]:
# Basic operations
# Create a tensor of values and add a number to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [35]:
# Multiply it by 10
tensor * 10


tensor([10, 20, 30])

In [36]:
# Tensors don't change unless reassigned
tensor

tensor([1, 2, 3])

In [37]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [38]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [39]:
# Can also use torch functions
torch.multiply(tensor, 10)


tensor([10, 20, 30])

In [40]:
# Original tensor is still unchanged
tensor

tensor([1, 2, 3])

In [42]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1 ->1, 2 ->2)
print(tensor, "*", tensor)
print("Equals:",  tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


# Matrix multiplication (is all you need)

In [44]:
import torch
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

In [45]:
# Element-wise matrix multiplication
tensor * tensor

tensor([1, 4, 9])

In [46]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [47]:
# Can also use the "@" symbol for matrix multiplication, though not recommended
tensor @ tensor

tensor(14)

In [51]:
%%time
# Matrix multiplication by hand
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
value

CPU times: total: 0 ns
Wall time: 291 μs


tensor(14)