In [1]:
import torch
from torch import nn # nn contains all of PyTorch's building blocks for neural networks
import matplotlib.pyplot as plt

ModuleNotFoundError: No module named 'torch'

In [ ]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
#  Get the  python number within a tensor (only works with one-element tensors)
scalar.item()

7

In [ ]:
scalar.ndim

0

In [ ]:
import numpy as np

In [ ]:
one = np.array(1)
print(one.shape)

()


In [ ]:
print(one.ndim)


0


In [ ]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
# check the number of dimensions of vectors
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
# Check number of dimension
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR.ndim

3

In [ ]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3,5)
random_tensor

tensor([[0.8167, 0.6465, 0.4906, 0.3710, 0.6024],
        [0.6106, 0.1816, 0.5661, 0.4832, 0.5351],
        [0.9914, 0.0537, 0.2317, 0.7766, 0.6513]])

In [ ]:
random_tensor.dtype

torch.float32

In [ ]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([224, 224, 3]), 3)

In [ ]:
# use torch.arrange(), torch.range() is deprecated
zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future

NameError: name 'torch' is not defined