In [66]:
import torch
from torch import nn # nn contains all of PyTorch's building blocks for neural networks
import matplotlib.pyplot as plt

In [67]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [68]:
#  Get the  python number within a tensor (only works with one-element tensors)
scalar.item()

7

In [69]:
scalar.ndim

0

In [70]:
import numpy as np

In [71]:
one = np.array(1)
print(one.shape)

()


In [72]:
print(one.ndim)


0


In [73]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [74]:
# check the number of dimensions of vectors
vector.ndim

1

In [75]:
vector.shape

torch.Size([2])

In [76]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [77]:
# Check number of dimension
MATRIX.ndim

2

In [78]:
MATRIX.shape

torch.Size([2, 2])

In [79]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [80]:
TENSOR.shape

torch.Size([1, 3, 3])

In [81]:
TENSOR.ndim

3

In [82]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3,5)
random_tensor

tensor([[0.9131, 0.1349, 0.1490, 0.6687, 0.0775],
        [0.8567, 0.1202, 0.4914, 0.3930, 0.0641],
        [0.9444, 0.0639, 0.5699, 0.6595, 0.0976]])

In [83]:
random_tensor.dtype

torch.float32

In [84]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([224, 224, 3]), 3)

In [85]:
# use torch.arrange(), torch.range() is deprecated
zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future

C:\Users\user322\AppData\Local\Temp\ipykernel_3344\261240356.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future


In [86]:
# Zeros and Ones
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [87]:
# create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

# Creating a range and tensors like

In [88]:
# Sometimes you want a range of numbers such as 1 to 10 or 0 to 100
# you can (start, end , step) 

# Use torch.arange(), torch.range() is deprecated
zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future

# Create  a range of values 0 to 10
zeros_to_ten = torch.arange(start=0, end=10, step=1)
zeros_to_ten

C:\Users\user322\AppData\Local\Temp\ipykernel_3344\3847230605.py:5: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
# sometimes you might want one tensor of certain type with the same shape as another tensor

# can also create a tensor of zeroes similar to another tensor
ten_zeros = torch.zeros_like(input=zeros_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor datatypes

In [90]:
# Default datatypes for tensors is float32
float_32_tensor = torch.tensor([9.0, 9.0, 9.0],
                               dtype=None, 
                               device=None,
                               requires_grad=False)  
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [91]:

float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float32) # torch.half would also work
float_16_tensor.dtype

torch.float32

# Getting information from tensors

In [92]:
# Create a tensor 
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"The datatype: {some_tensor.dtype}")
print(f"The devices: {some_tensor.device}")
print(f"The shape: {some_tensor.shape}")

tensor([[0.0900, 0.0816, 0.7481, 0.8661],
        [0.7585, 0.6861, 0.6460, 0.3282],
        [0.2649, 0.4783, 0.5380, 0.1231]])
The datatype: torch.float32
The devices: cpu
The shape: torch.Size([3, 4])


# Manipulating tensors (tensor operations)

In [93]:
# Basic operations
# Create a tensor of values and add a number to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [94]:
# Multiply it by 10
tensor * 10


tensor([10, 20, 30])

In [95]:
# Tensors don't change unless reassigned
tensor

tensor([1, 2, 3])

In [96]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [97]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [98]:
# Can also use torch functions
torch.multiply(tensor, 10)


tensor([10, 20, 30])

In [99]:
# Original tensor is still unchanged
tensor

tensor([1, 2, 3])

In [100]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1 ->1, 2 ->2)
print(tensor, "*", tensor)
print("Equals:",  tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


# Matrix multiplication (is all you need)

In [101]:
import torch
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

In [102]:
# Element-wise matrix multiplication
tensor * tensor

tensor([1, 4, 9])

In [103]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [104]:
# Can also use the "@" symbol for matrix multiplication, though not recommended
tensor @ tensor

tensor(14)

In [108]:
%%time
# Matrix multiplication by hand
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: total: 0 ns
Wall time: 190 μs


tensor(14)

In [ ]:
%%time
torch.matmul(tensor, tensor)

tensor(14)

# One of the most common errors in deep learning (shape errors)

In [110]:
# Shape need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)
                         
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)
torch.matmul(tensor_A, tensor_B) # (this will error)                         

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [111]:
# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [112]:
# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)


tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [ ]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A =")